#!/usr/bin/env python3
"""
Newton Worker - Connects to 'newton' consumer group
Handles both new messages (>) and pending messages
Actually executes tasks using LLM code generation
"""
import sys
import os
import redis
import json
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

STREAM_KEY = "smartfactory:stream:tasks"
RESULTS_KEY = "smartfactory:stream:results"
GROUP_NAME = "newton"
CONSUMER_NAME = "newton"

# LLM Configuration (optional)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-3.5-turbo")

def call_llm(prompt: str) -> str:
    """调用 LLM 生成代码"""
    if not OPENAI_API_KEY:
        # 无 API key，返回模拟结果
        return f"# Mock code for: {prompt[:50]}...\nprint('Task executed')"
    
    try:
        import openai
        client = openai.OpenAI(api_key=OPENAI_API_KEY)
        response = client.chat.completions.create(
            model=OPENAI_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"[Newton] LLM error: {e}")
        return f"# LLM error: {e}"


def handle_task(task_data):
    """
    处理任务：解析需求，调用 LLM 生成代码，写入文件
    """
    task = task_data.get("task", {})
    task_id = task.get("id", "unknown")
    title = task.get("title", "")
    requirements = task.get("requirements", "")
    project_id = task_data.get("project_id") or task.get("project_id", "default")
    
    print(f"[Newton] Processing: {task_id} - {title}", flush=True)
    
    # 构建 LLM prompt
    prompt = f"""作为开发者，实现以下任务：

任务: {title}
需求: {requirements}
项目ID: {project_id}

请生成 Python 代码实现这个任务。只输出代码，不要解释。"""
    
    # 调用 LLM
    generated_code = call_llm(prompt)
    
    # 确定输出路径
    project_dir = f"/home/pi/.openclaw/workspace/{project_id}" if project_id != "default" else "/tmp"
    output_file = os.path.join(project_dir, f"{task_id}.py")
    
    try:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, "w") as f:
            f.write(f"# Task: {task_id}\n# Title: {title}\n# Generated by Newton Worker\n\n")
            f.write(generated_code)
        print(f"[Newton] Wrote code to {output_file}", flush=True)
    except Exception as e:
        print(f"[Newton] File write error: {e}", flush=True)
        output_file = None
    
    return {
        "status": "completed",
        "task_id": task_id,
        "title": title,
        "output_file": output_file,
        "worker": CONSUMER_NAME,
    }


def process_message(msg_id, data, r):
    """处理单条消息"""
    try:
        task_data = json.loads(data["data"])
        print(f"[Newton] Got task: {task_data.get('task',{}).get('id','?')}", flush=True)
        result = handle_task(task_data)
        result["msg_id"] = msg_id
        
        # 发布结果到 results stream
        r.xadd(RESULTS_KEY, {"data": json.dumps(result)})
        # ACK 确认
        r.xack(STREAM_KEY, GROUP_NAME, msg_id)
        print(f"[Newton] Completed: {result['task_id']}", flush=True)
        return True
    except json.JSONDecodeError as e:
        print(f"[Newton] JSON decode error: {e}", flush=True)
        # 标记为 dead letter
        r.xadd(f"{STREAM_KEY}:dlq", {"data": data.get("data", ""), "error": str(e)})
        r.xack(STREAM_KEY, GROUP_NAME, msg_id)
        return False
    except Exception as e:
        print(f"[Newton] Error: {e}", flush=True)
        return False


def main():
    print("[Newton] Starting worker...", flush=True)
    r = redis.from_url(os.getenv("REDIS_URL", "redis://localhost:6379"), decode_responses=True)
    print(f"[Newton] Connected to Redis", flush=True)
    
    # 确保 consumer group 存在
    try:
        r.xgroup_create(STREAM_KEY, GROUP_NAME, id="$", mkstream=True)
        print(f"[Newton] Created consumer group: {GROUP_NAME}", flush=True)
    except redis.ResponseError as e:
        if "BUSYGROUP" in str(e):
            print(f"[Newton] Consumer group {GROUP_NAME} already exists", flush=True)
        else:
            raise(e)
    
    print(f"[Newton] Listening to group '{GROUP_NAME}', consumer '{CONSUMER_NAME}'...", flush=True)
    print(f"[Newton] LLM available: {bool(OPENAI_API_KEY)}", flush=True)
    
    while True:
        try:
            # Step 1: 处理 pending 消息（之前失败的任务）
            pending = r.xreadgroup(GROUP_NAME, CONSUMER_NAME, {STREAM_KEY: "0"}, count=5, block=100)
            for stream, entries in pending:
                for msg_id, data in entries:
                    process_message(msg_id, data, r)
            
            # Step 2: 读取新消息
            msgs = r.xreadgroup(GROUP_NAME, CONSUMER_NAME, {STREAM_KEY: ">"}, count=1, block=3000)
            for stream, entries in msgs:
                for msg_id, data in entries:
                    process_message(msg_id, data, r)
                        
        except KeyboardInterrupt:
            print("[Newton] Shutting down...", flush=True)
            break
        except Exception as e:
            print(f"[Newton] Error: {e}", flush=True)
            continue


if __name__ == "__main__":
    main()
